#include "core/trainer_builder.h"
#include <Windows.h>
#include <fstream>
#include <sstream>

namespace memforge {

static std::string EscapeString(const std::string& s) {
    std::string out;
    for (char c : s) {
        if (c == '\\') out += "\\\\";
        else if (c == '"') out += "\\\"";
        else if (c == '\n') out += "\\n";
        else if (c == '\r') out += "\\r";
        else out += c;
    }
    return out;
}

static std::string VkToDefine(int vk) {
    if (vk >= VK_F1 && vk <= VK_F12) {
        return "VK_F" + std::to_string(vk - VK_F1 + 1);
    }
    if (vk >= VK_NUMPAD0 && vk <= VK_NUMPAD9) {
        return "VK_NUMPAD" + std::to_string(vk - VK_NUMPAD0);
    }
    char buf[16];
    snprintf(buf, sizeof(buf), "0x%02X", vk);
    return buf;
}

bool TrainerBuilder::GenerateTrainerSource(const TrainerConfig& config,
                                            const std::string& outputPath) {
    std::ofstream out(outputPath);
    if (!out.is_open()) return false;

    out << "// Auto-generated trainer for " << config.gameName << "\n";
    out << "// Generated by MemForge Trainer Builder\n";
    out << "// Author: " << config.author << "\n\n";

    out << "#define WIN32_LEAN_AND_MEAN\n";
    out << "#define NOMINMAX\n";
    out << "#include <Windows.h>\n";
    out << "#include <TlHelp32.h>\n";
    out << "#include <cstdio>\n";
    out << "#include <cstdint>\n";
    out << "#include <cstring>\n";
    out << "#include <vector>\n\n";

    // Helper: find process
    out << "static DWORD FindProcess(const char* name) {\n";
    out << "    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);\n";
    out << "    if (snap == INVALID_HANDLE_VALUE) return 0;\n";
    out << "    PROCESSENTRY32W pe = {};\n";
    out << "    pe.dwSize = sizeof(pe);\n";
    out << "    DWORD pid = 0;\n";
    out << "    if (Process32FirstW(snap, &pe)) {\n";
    out << "        do {\n";
    out << "            char narrow[MAX_PATH] = {};\n";
    out << "            WideCharToMultiByte(CP_UTF8, 0, pe.szExeFile, -1, narrow, MAX_PATH, nullptr, nullptr);\n";
    out << "            if (_stricmp(narrow, name) == 0) { pid = pe.th32ProcessID; break; }\n";
    out << "        } while (Process32NextW(snap, &pe));\n";
    out << "    }\n";
    out << "    CloseHandle(snap);\n";
    out << "    return pid;\n";
    out << "}\n\n";

    // Helper: AOB scan
    out << "static uintptr_t AobScan(HANDLE hProc, const uint8_t* pat, const bool* mask, size_t len) {\n";
    out << "    MEMORY_BASIC_INFORMATION mbi = {};\n";
    out << "    uintptr_t addr = 0;\n";
    out << "    while (VirtualQueryEx(hProc, (LPCVOID)addr, &mbi, sizeof(mbi))) {\n";
    out << "        if (mbi.State == MEM_COMMIT && !(mbi.Protect & PAGE_GUARD) &&\n";
    out << "            (mbi.Protect & (PAGE_READWRITE|PAGE_READONLY|PAGE_EXECUTE_READ|PAGE_EXECUTE_READWRITE))) {\n";
    out << "            std::vector<uint8_t> buf(mbi.RegionSize);\n";
    out << "            SIZE_T bytesRead = 0;\n";
    out << "            if (ReadProcessMemory(hProc, mbi.BaseAddress, buf.data(), mbi.RegionSize, &bytesRead)) {\n";
    out << "                for (size_t i = 0; i + len <= bytesRead; i++) {\n";
    out << "                    bool match = true;\n";
    out << "                    for (size_t j = 0; j < len; j++) {\n";
    out << "                        if (mask[j] && buf[i+j] != pat[j]) { match = false; break; }\n";
    out << "                    }\n";
    out << "                    if (match) return (uintptr_t)mbi.BaseAddress + i;\n";
    out << "                }\n";
    out << "            }\n";
    out << "        }\n";
    out << "        addr = (uintptr_t)mbi.BaseAddress + mbi.RegionSize;\n";
    out << "        if (addr == 0) break;\n";
    out << "    }\n";
    out << "    return 0;\n";
    out << "}\n\n";

    // Helper: write memory
    out << "static bool WriteMem(HANDLE hProc, uintptr_t addr, const void* data, size_t size) {\n";
    out << "    DWORD oldProt = 0;\n";
    out << "    VirtualProtectEx(hProc, (LPVOID)addr, size, PAGE_EXECUTE_READWRITE, &oldProt);\n";
    out << "    SIZE_T written = 0;\n";
    out << "    bool ok = WriteProcessMemory(hProc, (LPVOID)addr, data, size, &written) != 0;\n";
    out << "    VirtualProtectEx(hProc, (LPVOID)addr, size, oldProt, &oldProt);\n";
    out << "    return ok;\n";
    out << "}\n\n";

    // Helper: NOP
    out << "static bool NopBytes(HANDLE hProc, uintptr_t addr, size_t count) {\n";
    out << "    std::vector<uint8_t> nops(count, 0x90);\n";
    out << "    return WriteMem(hProc, addr, nops.data(), count);\n";
    out << "}\n\n";

    // Console color helpers
    out << "static void SetColor(int color) {\n";
    out << "    SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), (WORD)color);\n";
    out << "}\n\n";

    // Main function
    out << "int main() {\n";
    out << "    SetConsoleTitleA(\"" << EscapeString(config.trainerName) << "\");\n";
    out << "    SetColor(11);\n";
    out << "    printf(\"==========================================\\n\");\n";
    out << "    printf(\" " << EscapeString(config.trainerName) << "\\n\");\n";
    out << "    printf(\" for " << EscapeString(config.gameName) << "\\n\");\n";
    out << "    printf(\" by " << EscapeString(config.author) << "\\n\");\n";
    out << "    printf(\"==========================================\\n\\n\");\n";
    out << "    SetColor(7);\n\n";

    out << "    printf(\"Waiting for " << EscapeString(config.gameExe) << "...\\n\");\n";
    out << "    DWORD pid = 0;\n";
    out << "    while (!(pid = FindProcess(\"" << EscapeString(config.gameExe) << "\"))) { Sleep(500); }\n\n";

    out << "    HANDLE hProc = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid);\n";
    out << "    if (!hProc) { printf(\"Failed to open process!\\n\"); system(\"pause\"); return 1; }\n\n";

    out << "    SetColor(10);\n";
    out << "    printf(\"Attached to PID %lu\\n\\n\", pid);\n";
    out << "    SetColor(7);\n\n";

    // Register hotkeys
    out << "    // Register hotkeys\n";

    for (size_t i = 0; i < config.cheats.size(); i++) {
        auto& cheat = config.cheats[i];
        if (cheat.hotkeyVk != 0) {
            std::string mods = "0";
            if (cheat.hotkeyCtrl) mods = "MOD_CONTROL";
            if (cheat.hotkeyAlt) {
                if (mods == "0") mods = "MOD_ALT";
                else mods += " | MOD_ALT";
            }
            out << "    RegisterHotKey(NULL, " << (i + 1) << ", " << mods
                << ", " << VkToDefine(cheat.hotkeyVk) << ");\n";
        }
    }

    out << "\n    printf(\"Hotkeys:\\n\");\n";
    for (size_t i = 0; i < config.cheats.size(); i++) {
        auto& cheat = config.cheats[i];
        out << "    printf(\"  [" << (i + 1) << "] " << EscapeString(cheat.name) << "\\n\");\n";
    }
    out << "    printf(\"\\nPress hotkeys to toggle cheats.\\n\\n\");\n\n";

    // Generate cheat state arrays
    size_t cheatCount = config.cheats.empty() ? 1 : config.cheats.size();
    out << "    bool cheatActive[" << cheatCount << "] = {};\n";
    out << "    uintptr_t cheatAddr[" << cheatCount << "] = {};\n";
    out << "    uint8_t origBytes[" << cheatCount << "][64] = {};\n\n";

    // AOB scan for each cheat
    for (size_t i = 0; i < config.cheats.size(); i++) {
        auto& cheat = config.cheats[i];
        if (cheat.aobPattern.empty()) continue;

        // Parse pattern into static arrays
        out << "    // Scan for: " << cheat.name << "\n";
        out << "    {\n";

        // Emit pattern bytes and mask
        std::istringstream iss(cheat.aobPattern);
        std::string token;
        std::vector<std::string> tokens;
        while (iss >> token) tokens.push_back(token);

        out << "        static const uint8_t pat[] = { ";
        for (size_t j = 0; j < tokens.size(); j++) {
            if (tokens[j] == "??" || tokens[j] == "?") {
                out << "0x00";
            } else {
                out << "0x" << tokens[j];
            }
            if (j + 1 < tokens.size()) out << ", ";
        }
        out << " };\n";

        out << "        static const bool mask[] = { ";
        for (size_t j = 0; j < tokens.size(); j++) {
            out << ((tokens[j] == "??" || tokens[j] == "?") ? "false" : "true");
            if (j + 1 < tokens.size()) out << ", ";
        }
        out << " };\n";

        out << "        cheatAddr[" << i << "] = AobScan(hProc, pat, mask, " << tokens.size() << ");\n";
        if (cheat.aobOffset != 0) {
            out << "        if (cheatAddr[" << i << "]) cheatAddr[" << i << "] += " << cheat.aobOffset << ";\n";
        }
        out << "        if (cheatAddr[" << i << "]) {\n";
        out << "            SIZE_T br = 0;\n";

        size_t readSize = 4;
        if (cheat.type == TrainerCheat::CheatType::NopBytes) {
            readSize = (cheat.nopCount > 0) ? cheat.nopCount : tokens.size();
        }
        out << "            ReadProcessMemory(hProc, (LPCVOID)cheatAddr[" << i << "], origBytes[" << i << "], " << readSize << ", &br);\n";
        out << "            SetColor(10); printf(\"  [OK] " << EscapeString(cheat.name) << " found at 0x%llX\\n\", (unsigned long long)cheatAddr[" << i << "]); SetColor(7);\n";
        out << "        } else {\n";
        out << "            SetColor(12); printf(\"  [!!] " << EscapeString(cheat.name) << " not found\\n\"); SetColor(7);\n";
        out << "        }\n";
        out << "    }\n\n";
    }

    // Message loop for hotkeys
    out << "    printf(\"\\nTrainer ready. Press hotkeys to toggle.\\n\");\n";
    out << "    MSG msg;\n";
    out << "    while (GetMessage(&msg, NULL, 0, 0)) {\n";
    out << "        if (msg.message == WM_HOTKEY) {\n";
    out << "            int idx = (int)msg.wParam - 1;\n";
    out << "            if (idx >= 0 && idx < " << config.cheats.size() << " && cheatAddr[idx]) {\n";
    out << "                cheatActive[idx] = !cheatActive[idx];\n";
    out << "                if (cheatActive[idx]) {\n";

    // Apply cheat
    for (size_t i = 0; i < config.cheats.size(); i++) {
        auto& cheat = config.cheats[i];
        out << "                    ";
        if (i > 0) out << "else ";
        out << "if (idx == " << i << ") {\n";

        switch (cheat.type) {
            case TrainerCheat::CheatType::NopBytes: {
                size_t nc = (cheat.nopCount > 0) ? cheat.nopCount : 1;
                out << "                        NopBytes(hProc, cheatAddr[" << i << "], " << nc << ");\n";
                break;
            }
            case TrainerCheat::CheatType::FreezeValue:
            case TrainerCheat::CheatType::SetValue: {
                if (cheat.valueType == "float") {
                    out << "                        float v = " << cheat.value << "f;\n";
                    out << "                        WriteMem(hProc, cheatAddr[" << i << "], &v, sizeof(v));\n";
                } else if (cheat.valueType == "double") {
                    out << "                        double v = " << cheat.value << ";\n";
                    out << "                        WriteMem(hProc, cheatAddr[" << i << "], &v, sizeof(v));\n";
                } else if (cheat.valueType == "int64") {
                    out << "                        int64_t v = " << cheat.value << "LL;\n";
                    out << "                        WriteMem(hProc, cheatAddr[" << i << "], &v, sizeof(v));\n";
                } else {
                    out << "                        int32_t v = " << cheat.value << ";\n";
                    out << "                        WriteMem(hProc, cheatAddr[" << i << "], &v, sizeof(v));\n";
                }
                break;
            }
            default:
                break;
        }
        out << "                    }\n";
    }

    out << "                    SetColor(10); printf(\"[ON]  Cheat %d activated\\n\", idx+1); SetColor(7);\n";
    out << "                } else {\n";

    // Restore original bytes
    for (size_t i = 0; i < config.cheats.size(); i++) {
        auto& cheat = config.cheats[i];
        out << "                    ";
        if (i > 0) out << "else ";
        out << "if (idx == " << i << ") {\n";

        size_t restoreSize = 4;
        if (cheat.type == TrainerCheat::CheatType::NopBytes) {
            restoreSize = (cheat.nopCount > 0) ? cheat.nopCount : 1;
        }
        out << "                        WriteMem(hProc, cheatAddr[" << i << "], origBytes[" << i << "], " << restoreSize << ");\n";
        out << "                    }\n";
    }

    out << "                    SetColor(12); printf(\"[OFF] Cheat %d deactivated\\n\", idx+1); SetColor(7);\n";
    out << "                }\n";
    out << "            }\n";
    out << "        }\n";
    out << "    }\n\n";

    out << "    CloseHandle(hProc);\n";
    out << "    return 0;\n";
    out << "}\n";

    out.close();
    return true;
}

bool TrainerBuilder::GenerateBuildScript(const std::string& sourcePath,
                                          const std::string& outputExePath) {
    // Generate a .bat that calls cl.exe
    std::string batPath = outputExePath;
    size_t dotPos = batPath.rfind('.');
    if (dotPos != std::string::npos) {
        batPath = batPath.substr(0, dotPos) + "_build.bat";
    } else {
        batPath += "_build.bat";
    }

    std::ofstream bat(batPath);
    if (!bat.is_open()) return false;

    bat << "@echo off\n";
    bat << "cl.exe /nologo /EHsc /std:c++20 /O2 /DWIN32_LEAN_AND_MEAN /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS ";
    bat << "\"" << sourcePath << "\" ";
    bat << "/Fe:\"" << outputExePath << "\" ";
    bat << "/link user32.lib kernel32.lib\n";
    bat << "if %ERRORLEVEL% NEQ 0 (\n";
    bat << "    echo Build failed!\n";
    bat << "    pause\n";
    bat << ") else (\n";
    bat << "    echo Build succeeded: " << outputExePath << "\n";
    bat << ")\n";

    bat.close();
    return true;
}

bool TrainerBuilder::BuildTrainer(const TrainerConfig& config,
                                   const std::string& outputExePath) {
    // Generate source file
    std::string srcPath = outputExePath;
    size_t dotPos = srcPath.rfind('.');
    if (dotPos != std::string::npos) {
        srcPath = srcPath.substr(0, dotPos) + ".cpp";
    } else {
        srcPath += ".cpp";
    }

    if (!GenerateTrainerSource(config, srcPath)) return false;

    // Try to build using cl.exe via CreateProcess
    std::string cmdLine = "cl.exe /nologo /EHsc /std:c++20 /O2 "
        "/DWIN32_LEAN_AND_MEAN /DNOMINMAX /D_CRT_SECURE_NO_WARNINGS "
        "\"" + srcPath + "\" /Fe:\"" + outputExePath + "\" "
        "/link user32.lib kernel32.lib";

    STARTUPINFOA si = {};
    si.cb = sizeof(si);
    si.dwFlags = STARTF_USESHOWWINDOW;
    si.wShowWindow = SW_HIDE;

    PROCESS_INFORMATION pi = {};

    // Need mutable buffer for CreateProcessA
    std::vector<char> cmdBuf(cmdLine.begin(), cmdLine.end());
    cmdBuf.push_back('\0');

    BOOL ok = CreateProcessA(nullptr, cmdBuf.data(), nullptr, nullptr,
                              FALSE, CREATE_NO_WINDOW, nullptr, nullptr,
                              &si, &pi);
    if (!ok) return false;

    // Wait for compilation
    WaitForSingleObject(pi.hProcess, 30000); // 30 second timeout

    DWORD exitCode = 1;
    GetExitCodeProcess(pi.hProcess, &exitCode);

    CloseHandle(pi.hProcess);
    CloseHandle(pi.hThread);

    return exitCode == 0;
}

} // namespace memforge
